default_language_version:
  python: python3.9

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: debug-statements
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        name: Bandit security scanner
        language_version: python3
        entry: bandit -r .
        types: [python]
        args: ['-iii', '-ll'] # report only issues with high confidence and of medium or above severity

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
      - id: mypy
        args: ['--strict']

  # - repo: https://github.com/google/pytype
  #   rev: '2023.06.02'
  #   hooks:
  #     - id: pytype
  #       name: Pytype type checker
  #       language: system
  #       entry: pytype
  #       types: [python]
  #       args: ['--disable=import-error']

  - repo: https://github.com/mattseymour/pre-commit-pytype
    rev: '2023.5.8'
    hooks:
      - id: pytype
        language: system
        args:
          - "-j"
          - "auto"
          - "--disable=import-error"

  - repo: local
    hooks:
      - id: django-test
        name: Django test
        entry: python manage.py test
        language: system
        pass_filenames: false
        types: [python]

      - id: isort
        name: isort import sorter
        entry: isort
        language: system
        types: [python]
        args:
          - --recursive
          - .
          - --skip
          - .tox
          - .git
          - __init__.py
          - __pycache__
          - fixtures
          - "*.pyc"
          - .cache
          - migrations
          - manage.py
          - .venv
          - --django

      - id: black
        name: Black code formatter
        entry: black .
        language: system
        types: [python]
        pass_filenames: false
        args: ['--exclude', '.tox', '.git', '__init__.py', '__pycache__', 'fixtures', '*.pyc', '.cache', 'migrations', 'manage.py', '.venv']

      # - id: pytype
      #   name: Pytype
      #   entry: pytype
      #   language: system
      #   types: [python]
      #   args:
      #     - '--jobs=auto'
      #     - '--keep-going'
      #   files: \.py$

      - id: tox
        name: tox
        entry: tox
        language: system
        always_run: true
        pass_filenames: false
        stages: [commit]

exclude: '\.venv'
