# Generated by Django 4.2.1 on 2023-06-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authy", "0006_customtoken_verified_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customtoken",
            name="verified_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
