# Generated by Django 4.2.1 on 2023-06-15 16:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("authy", "0007_alter_customtoken_verified_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="customtoken",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="customtoken",
            name="key",
            field=models.CharField(max_length=40, verbose_name="Key"),
        ),
    ]
