# Generated by Django 4.2.1 on 2023-06-15 16:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authy", "0008_customtoken_id_alter_customtoken_key"),
        ("authy", "0009_alter_customtoken_id"),
    ]

    operations = []
