# Generated by Django 4.2.1 on 2023-06-15 19:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("authy", "0010_merge_20230615_1716"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customtoken",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                serialize=False,
                unique=True,
                verbose_name="ID",
            ),
        ),
    ]
