# Generated by Django 4.2.1 on 2023-06-15 20:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("authy", "0011_alter_customtoken_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customtoken",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                serialize=False,
                unique=True,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="regToken",
            field=models.CharField(
                blank=True,
                help_text="Token user used to validate account.",
                max_length=40,
                null=True,
                verbose_name="Token",
            ),
        ),
    ]
